services:
  mmrs_controller:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: mmrs_controller_sim
    user: ros
    network_mode: host
    ipc: host
    # networks:
    #   - no-internet
    environment:
      - DISPLAY=unix$DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID
    volumes:
      - ./docker/turtlebot3:/home/ros/turtlebot3
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true 
    tty: true

# networks:
#   no-internet:
#     internal: true